### ISSUE TITLE
Remove deleted posts permanently from UI?

### ISSUE THREAD

**Issue by neutrinonerd3333** [edemaine/coauthor#166] opened 2017-03-01 21:50 UTC
Currently, deleted posts just live on in the UI as posts that can be undeleted at any time--- these can clutter up the interface and get really annoying. (Unless I'm missing something, and they disappear after some time limit?)

-- txz

**Comment by edemaine** [comment] 2017-03-02 00:43
You're not missing anything -- that's the intended behavior, as we never want to lose any work.  But I agree it clutters the interface; that's the idea behind issue #84.  I'm hoping to implement that soon...  Closing this issue as a duplicate of that.

**Closed by edemaine** 2017-03-02 00:43 UTC
