### ISSUE TITLE
Invite/share links

### ISSUE THREAD

**Issue by slef** [edemaine/coauthor#309] opened 2018-05-22 20:28 UTC
When starting a discussion or a thread with a new set of people who might or might not be on coauthor already, it would be cool to be able to send them an invite link which automatically adds them to the ACL of that group or thread. 
It might be safer if the link is usable a fixed number of times, or if it expires, or if the signup must be confirmed by the admin, or if the admin gets notified.

**Comment by edemaine** [comment] 2018-07-07 21:38
I agree. This is a duplicate of #42, which has some old implementation ideas. Let's continue any discussion there.

**Closed by edemaine** 2018-07-07 21:38 UTC
Labels: duplicate
