### ISSUE TITLE
Support HEIC

### ISSUE THREAD

**Issue by sualehasif** [edemaine/coauthor#603] opened 2022-06-23 22:23 UTC
iPhones use HEIC by default so posting a photo directly from iPhone (using handoff or otherwise doesnt really work :(.) Given their prevelance, it would be nice to support it.

<img width="1221" alt="Screen Shot 2022-06-23 at 3 22 28 PM" src="https://user-images.githubusercontent.com/28659689/175424937-e2bd74d7-aa64-47c5-b776-50a5ab12bee7.png">

**Comment by edemaine** [comment] 2022-06-23 23:23
Duplicate of #580. If you have ideas for fixing, I'd appreciate them! HEIC is terrible. 🙁

**Closed** 2022-06-23 23:24 UTC
Labels: duplicate, enhancement
