### ISSUE TITLE
LaTeX rendering not using the right font?

### ISSUE THREAD

**Issue by mwijaya** [edemaine/coauthor#477] opened 2020-07-14 13:12 UTC
## What's wrong?
A clear and concise description of what the bug is, expected behavior, etc.
The font used for LaTeX rendering is different from the standard one. I started noticing this two days ago. Please see the screenshots below.

## Screenshots
If applicable, paste in screenshots of the bug.

Screenshot 1:
![Screenshot from 2020-07-14 08-44-06](https://user-images.githubusercontent.com/1936881/87427131-53416f00-c5ae-11ea-8112-0257b3c4fb90.png)

Screenshot 2:
![Screenshot from 2020-07-14 08-46-12](https://user-images.githubusercontent.com/1936881/87427256-8257e080-c5ae-11ea-8500-fd5a763280b7.png)

## Context
 - Device/OS:  Ubuntu 18.04.4 LTS
 - Browser:  Google Chrome 83.0.4103.116 (Official Build) (64-bit)
 - Coauthor server:  REU

**Comment by edemaine** [comment] 2020-07-14 16:27
Thanks for reporting this! This was caused by a failure to update the sanitizer after updating KaTeX, and KaTeX switching some class names in particular for regular italic text, making it turn roman. Oops. ☹️ 

Should be fixed now.

**Closed by edemaine** 2020-07-14 16:27 UTC
Labels: bug
